### ISSUE TITLE
docker buildx build failed on mac m2

### ISSUE THREAD

**Issue by hxgqh** [mingchen/docker-android-build-box#153]
git branch: master
Computer & CPU: MacOS M2

`
ERROR: failed to solve: process "/bin/sh -c echo \"installing: $(cat $PACKAGES_FILENAME)\" &&     . /etc/jdk.env &&     yes | ${ANDROID_SDK_MANAGER} ${DEBUG:+--verbose} --package_file=$PACKAGES_FILENAME > /dev/null" did not complete successfully: exit code: 1
`

**Comment by ddaniel-healthy** [comment]
solution?

**Comment by ddaniel-healthy** [comment]
@mingchen ?

**Comment by ddaniel-healthy** [comment]
<img width="262" alt="Screenshot 2023-11-01 at 12 32 19" src="https://github.com/mingchen/docker-android-build-box/assets/125867920/9eda01e3-9076-4d23-af69-c54180b087f3">

you should add support for arm64v8

**Comment by ddaniel-healthy** [comment]
https://github.com/docker-library/hello-world

**Comment by master-bob** [comment]
> <img alt="Screenshot 2023-11-01 at 12 32 19" width="262" src="https://user-images.githubusercontent.com/125867920/279649011-9eda01e3-9076-4d23-af69-c54180b087f3.png">
> 
> yes it not your image, but your as the same error tag. you should add support for arm64v8

When reading this, it initially came across as disrespectful. I asked for the full log as an attempt to **help ya'll**. Maybe there's some cultural issues at play here??

Okay...I'm not sure what you mean by "it not your image"? Like the screenshot is not the image? Okay, but that doesn't help me understand what the problem is.

And then "the same error tag"... yes, okay. But without seeing the full log, and in particular the full `DEBUG`, there's nothing for me to do. The full log mind you, so from the point of the command being executed, all the output, the error, and then the last line is the new terminal input line.

I just thought that it would be worthwhile to see if the minimal build target completes on M2.

So this is what I need to be able to continue to help:
- The full build log, including the command run, the output, the error itself, and the new terminal line
- the build log using the build target "minimal"

Without those two, there is nothing for me to do. I don't have an M2, and per this [answer on StackExchange](https://apple.stackexchange.com/a/420121), I can't even emulate it.

**Comment by ddaniel-healthy** [comment]
Hi there, thanks for your time and effort.
Sorry, my mistake, about the log, i've tried what you asked but because its not working (I assume it crash even before it get to print something). So I sent you what I've seen as indicator what maybe cause it, and I forgot to mention it to you.
