### ISSUE TITLE
bash: line 1: ./gradlew: No such file or directory

### ISSUE THREAD

**Issue by artemrogov** [mingchen/docker-android-build-box#171]
I'm going to start building the project, as in the instructions for the box, go to the directory with the project, run the build command:

```
cd <android project directory>  # change working directory to your project root directory.
docker run --rm -v `pwd`:/project mingc/android-build-box bash -c 'cd /project; ./gradlew build'
```

At the output I get an error message:
`./gradlew: No such file or directory`

**Comment by master-bob** [comment]
This doesn't really seem to be an issue with this project, the docker-android-build-box, itself.

What this error is telling you is that when trying to execute, `./`, the file `gradlew` ([Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) it does not find this.

There is no included project within the docker-android-build-box outside the very basic test project, [test_projects/SampleProject](https://github.com/mingchen/docker-android-build-box/tree/master/test_projects/SampleProject). If you set the present directory to the aforementioned `SampleProject`, then the command, `./gradlew build`, would execute.

If your project requires gradle to be installed on the host system, I would suggest you switch to using the wrapper for the reasons mentioned in the above linked documentation.

As this issue is not for this docker-android-build-box, this ticket should be closed. @mingchen, please close this.
