### ISSUE TITLE
Impossible to run UI Tests

### ISSUE THREAD

**Issue by gderaco** [mingchen/docker-android-build-box#38]
I've tried to run a UI Test with Espresso but the simulator fail to start in the container.

**Comment by ozmium** [comment]
I have also noticed a problem in some newer versions of the Docker image `android-build-box`, where the Android ARM emulator will not launch on the build machine.

It took me a while to figure it out, but it seems that the problem is **caused by a bug in the newer versions of the Android Build Tools!**

Analysis
--------

1. Use this older version on your build machine, which was created on 4 November 2018:

        image: mingc/android-build-box:v1.4.0

2. Inside the docker image, list the files in the `$ANDROID_HOME/emulator` folder:

        ls -la $ANDROID_HOME/emulator/

3. You should see the output like this:

```sh
ls -la $ANDROID_HOME/emulator/
total 83956
drwxr-xr-x. 7 root root     4096 Jan  9  2019 .
drwxr-xr-x. 1 root root     4096 Jun 18 04:02 ..
-rw-r--r--. 1 root root      250 Jan  9  2019 android-info.txt
drwxr-xr-x. 2 root root     4096 Jan  9  2019 bin64
-rwxr-xr-x. 1 root root  3589936 Jan  9  2019 emulator
-rwxr-xr-x. 1 root root 32103120 Jan  9  2019 emulator64-arm
-rwxr-xr-x. 1 root root 12829272 Jan  9  2019 emulator64-crash-service
-rwxr-xr-x. 1 root root 32225904 Jan  9  2019 emulator64-x86
-rwxr-xr-x. 1 root root  3142984 Jan  9  2019 emulator-check
drwxr-xr-x. 3 root root     4096 Jan  9  2019 lib
drwxr-xr-x. 4 root root     4096 Jan  9  2019 lib64
-rwxr-xr-x. 1 root root    13846 Jan  9  2019 mksdcard
-rw-r--r--. 1 root root    38195 Jan  9  2019 NOTICE.txt
-rw-r--r--. 1 root root    17353 Jan  9  2019 package.xml
drwxr-xr-x. 3 root root     4096 Jan  9  2019 qemu
-rwxr-xr-x. 1 root root  1949016 Jan  9  2019 qemu-img
drwxr-xr-x. 2 root root     4096 Jan  9  2019 resources
-rw-r--r--. 1 root root      111 Jan  9  2019 source.properties
```

4. This set of files will work fine to launch the following ARM emulators: Android 5.1 (API 22), 5.0 (API 21), 4.4 (API 19), 4.1 (API 16), on Ubuntu Linux. Notice there is a file called **emulator64-arm**.

5. Repeat the same thing in a newer Docker image, created on 20 June 2020:

```sh
image: mingc/android-build-box:1.18.0
```

```sh
ls -la $ANDROID_HOME/emulator/
total 41120
drwxr-xr-x. 7 root root     4096 Jun 21 18:35 .
drwxr-xr-x. 1 root root     4096 Jun 21 22:04 ..
-rw-r--r--. 1 root root      250 Jun 21 18:35 android-info.txt
drwxr-xr-x. 2 root root     4096 Jun 21 18:35 bin64
-rwxr-xr-x. 1 root root 11590848 Jun 21 18:35 emulator
-rwxr-xr-x. 1 root root 16496056 Jun 21 18:35 emulator64-crash-service
-rwxr-xr-x. 1 root root   152080 Jun 21 18:35 emulator-check
-rwxr-xr-x. 1 root root 11711608 Jun 21 18:35 goldfish-webrtc-bridge
drwxr-xr-x. 3 root root     4096 Jun 21 18:35 lib
drwxr-xr-x. 6 root root     4096 Jun 21 18:35 lib64
-rw-r--r--. 1 root root      524 Jun 21 18:35 LICENSE
-rwxr-xr-x. 1 root root    10792 Jun 21 18:35 mksdcard
-rw-r--r--. 1 root root    33656 Jun 21 18:35 NOTICE.csv
-rw-r--r--. 1 root root   155383 Jun 21 18:35 NOTICE.txt
-rw-r--r--. 1 root root    17828 Jun 21 18:35 package.xml
drwxr-xr-x. 3 root root     4096 Jun 21 18:35 qemu
-rwxr-xr-x. 1 root root  1874464 Jun 21 18:35 qemu-img
drwxr-xr-x. 4 root root     4096 Jun 21 18:35 resources
-rw-r--r--. 1 root root      102 Jun 21 18:35 source.properties
```

6. Notice the files are different, with different file sizes, and importantly **emulator64-arm is no longer there.**

7. **This set of files will not work to launch the emulator**, even after successfully creating an emulator image. You will just see unclear error messages like this:

```
emulator: ERROR: This AVD's configuration is missing a kernel file!
Please ensure the file "kernel-ranchu" is in the same location as your system image.

emulator: ERROR: ANDROID_SDK_ROOT is undefined

emulator: ERROR: New emulator backend requires minimum kernel version 3.10+
(currently got lower). Please make sure you've got updated system images
and do not force the specific kernel image together with the engine version
```

 * https://stackoverflow.com/questions/58349492/please-ensure-the-file-kernel-ranchu-is-in-the-same-location-as-your-system-im
 * https://stackoverflow.com/questions/9712605/emulator-error-this-avds-configuration-is-missing-a-kernel-file
 * https://stackoverflow.com/questions/43433542/stuck-at-android-repositories-cfg-could-not-be-loaded

8. Why are there different emulator files in the different versions of `android-build-box`? **I believe the reason is because of the Android Build Tools.** It seems that when **"build-tools;29.0.2"** (or higher) is installed, the 'emulator' package will download a non-functioning one. Whereas when **"build-tools;28.0.2"** (or lower) is installed, the 'emulator' package will download a working one. You can view the text in `$ANDROID_HOME/emulator/source.properties` to see which Build Tools version is used. This problem also seems to happen on MacOS, where most of the ARM emulators no longer launch, when the newer build tools are installed.

Workaround - Copy the emulator folder from the older Docker image
----------

Copy the entire `"$ANDROID_HOME/emulator/"` folder from the old Docker image, when Build Tools 28 is installed. Zip it up and store the zip file somewhere externally. Then use this zip file in the new Docker image: So delete or rename the default "emulator" folder, then unzip to replace the "emulator" folder. It should work.
