### ISSUE TITLE
Error with ARM64 architecture built

### ISSUE THREAD

**Issue by Chris-home17** [mingchen/docker-android-build-box#95]
Hi Mingchen,

Great docker image ! Thank you for sharing. I've built it again on Apple M1 but I'm stuck with the next error:

```
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.
> Task :app:preBuild UP-TO-DATE
> Task :app:preAcceptance_de_localLandcapeDebugBuild UP-TO-DATE
> Task :app:compileAcceptance_de_localLandcapeDebugAidl NO-SOURCE
> Task :app:compileAcceptance_de_localLandcapeDebugRenderscript NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsAcceptance_de_localLandcapeDebug
> Task :app:dataBindingMergeGenClassesAcceptance_de_localLandcapeDebug
> Task :app:generateAcceptance_de_localLandcapeDebugResValues
> Task :app:generateAcceptance_de_localLandcapeDebugResources
> Task :app:injectCrashlyticsMappingFileIdAcceptance_de_localLandcapeDebug
> Task :app:processAcceptance_de_localLandcapeDebugGoogleServices
> Task :app:dataBindingTriggerAcceptance_de_localLandcapeDebug
> Task :app:generateAcceptance_de_localLandcapeDebugBuildConfig
AAPT2 aapt2-7.0.3-7396180-linux Daemon #0: Unexpected error output: qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
> Task :app:mergeAcceptance_de_localLandcapeDebugResources FAILED
> Task :app:javaPreCompileAcceptance_de_localLandcapeDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeAcceptance_de_localLandcapeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
   > AAPT2 aapt2-7.0.3-7396180-linux Daemon #0: Daemon startup failed
     This should not happen under normal circumstances, please file an issue if it does.

```

Hopefully someone can help me and tell me what I should do to fix this error.

Thank you very much.

Chris

**Comment by heyong1996** [comment]
need help

**Comment by master-bob** [comment]
Hmm, maybe using the `--platform linux/amd64` flag on docker pull and docker run will help?

**Comment by kar** [comment]
It seems to be getting stuck at random places when run with that argument. More precisely the gradle process gets stuck, in different stages every time.

**Comment by master-bob** [comment]
> It seems to be getting stuck at random places when run with that argument. More precisely the gradle process gets stuck, in different stages every time.

So then to be clear, you did a `docker build` or `pull`, and then a `docker run` specifying the platform in both. And when you did so gradle gets "stuck" in random places. Is that correct? Specifically `docker build / pull` and `docker run`, where **both** run with the `platform` argument?

What do you mean by it gets stuck? It hangs? Or are you getting a "qemu-x86_64" based error like in OP? or another error?

**Comment by kar** [comment]
I did `docker pull --platform linux/amd64`. It works fine always. Then `docker run`, more exact:

`➜  ~ docker run --platform linux/amd64 --rm -v `pwd`:/project mingc/android-build-box bash -c 'cd /project; ./gradlew assemble'`

.. in my project repo which would start compiling it.

The process starts and I can see gradle being downloaded. Then it seems to hang somewhere in this stage. The output seems to stop at various places one example:

`
Downloading https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
..............................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z/gradle-7.3.3-bin.zip to /root/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z/gradle-7.3.3/bin/gradle

Welcome to Gradle 7.3.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
`

I waited for like 30 minutes and it would not proceed. The project is fine otherwise and would normally compile within 1-2 minutes at most.

**Comment by master-bob** [comment]
Okay. That's helpful. 

Try running the gradlew with the `--info` and `--stacktrace` options; I don't recall but it could be one dash instead of two. That output should be helpful. There's also `--debug`, but it's incredibly verbose so I wouldn't suggest it.

**Comment by kar** [comment]
It really seems random where it stops.  I added the `--info`.  Now it got stuck very early:

````
Downloading https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
..............................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z/gradle-7.3.3-bin.zip to /root/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z/gradle-7.3.3/bin/gradle
```
 
... and another time it got much further in the gradle compilation process, but the output didn't seem like encountering any error, just halted.

**Comment by master-bob** [comment]
That's strange. I'm not sure what is happening. From there I would try with the `debug` flag to see if it gave more output. 

The other thought I had would be to add the platform specification directly to the Dockerfile and building it. When I searched this*, that was one of the solutions which was presented.

* it was something with `Unexpected error output: qemu-x86_64`.
